#!/usr/bin/env bash
# 1Panel container entrypoint.
#
# The embedded default app.yaml is mode=dev, so both binaries read a
# runtime config from <install_dir>/1panel/conf/app.yaml when it
# exists. We generate it from env on first boot (then it persists on
# the mounted volume). Agent must come up first — it owns the
# /etc/1panel/agent.sock that core reverse-proxies to.
set -euo pipefail

INSTALL_DIR="${PANEL_INSTALL_DIR:-/opt}"
CONF_DIR="${INSTALL_DIR}/1panel/conf"
mkdir -p "${CONF_DIR}" /etc/1panel

if [ ! -f "${CONF_DIR}/app.yaml" ]; then
    cat > "${CONF_DIR}/app.yaml" <<EOF
base:
  install_dir: ${INSTALL_DIR}
  mode: dev
  is_demo: false
  is_offline: false
  is_fxplay: false
  port: ${PANEL_PORT:-9999}
  username: ${PANEL_USERNAME:-admin}
  password: ${PANEL_PASSWORD:-admin123}
  version: v2.0.0

log:
  level: ${PANEL_LOG_LEVEL:-info}
  time_zone: ${TZ:-UTC}
  log_name: 1Panel
  log_suffix: .log
  max_backup: 10
EOF
    echo "[1panel] wrote ${CONF_DIR}/app.yaml (user=${PANEL_USERNAME:-admin}, port=${PANEL_PORT:-9999})"
fi

# Both binaries call common.LoadParams(), which greps KEY=value lines
# out of /usr/local/bin/1pctl (the upstream operator script, NOT in
# this source tree). agent/utils/xpack.LoadNodeInfo() reads BASE_DIR
# and ORIGINAL_VERSION this way *unconditionally* and panics if the
# file/keys are missing. Synthesize the minimal 1pctl it needs.
if [ ! -f /usr/local/bin/1pctl ] || ! grep -q '^BASE_DIR=' /usr/local/bin/1pctl; then
    cat > /usr/local/bin/1pctl <<EOF
#!/bin/sh
# Generated by the container entrypoint. Only the KEY=value lines
# below are consumed (via grep) by common.LoadParams().
BASE_DIR=${INSTALL_DIR}
ORIGINAL_PORT=${PANEL_PORT:-9999}
ORIGINAL_VERSION=v2.0.0
ORIGINAL_USERNAME=${PANEL_USERNAME:-admin}
ORIGINAL_PASSWORD=${PANEL_PASSWORD:-admin123}
ORIGINAL_ENTRANCE=${PANEL_ENTRANCE:-entrance}
LANGUAGE=${PANEL_LANGUAGE:-en}
PANEL_EDITION=community
EOF
    chmod 0755 /usr/local/bin/1pctl
    echo "[1panel] wrote /usr/local/bin/1pctl (BASE_DIR=${INSTALL_DIR})"
fi

# Agent first (creates the control socket); then core in the foreground.
/usr/local/bin/1panel-agent &
AGENT_PID=$!

for _ in $(seq 1 30); do
    [ -S /etc/1panel/agent.sock ] && break
    if ! kill -0 "${AGENT_PID}" 2>/dev/null; then
        echo "[1panel] agent exited before creating the socket" >&2
        exit 1
    fi
    sleep 1
done

# If core exits, take the container down (restart policy handles it);
# also reap the agent.
trap 'kill "${AGENT_PID}" 2>/dev/null || true' EXIT
exec /usr/local/bin/1panel-core
